SELECT * FROM DEPT; --DEPTNO 20 : DALLAS / DEPTNO 30 : CHICAGO
SELECT * FROM EMP;

SELECT ENAME,HIREDATE
FROM EMP
WHERE DEPTNO = '20'  -- DEPTNO 20 : DALLAS
OR DEPTNO = '30' -- DEPTNO 30 : CHICAGO
;

SELECT A.ENAME
     , A.HIREDATE 
     , B.LOC 
FROM  EMP A
    , DEPT B
WHERE B.LOC = 'DALLAS'
OR B.LOC = 'CHICAGO'
;
